package issues.i70;

public class DatabaseHelper_min {
    public static void sample3() {
        consumeStr(
                "CREATE PROCEDURE verifyUserPassword(IN username_ varchar(50), IN password_ varchar(50))"
                        + " READS SQL DATA"
                        + " DYNAMIC RESULT SETS 1"
                        + " BEGIN ATOMIC"
                        + " DECLARE resultSet SCROLL CURSOR WITH HOLD WITH RETURN FOR SELECT * FROM USERS WHERE USERNAME = username_ AND PASSWORD = password_;"
                        + " OPEN resultSet;"
                        + "END;");
    }

    public static void sample4() {
        consumeStr(
                "create table EMPLOYEE ("
                        + "	   id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,"
                        + "	   first_name VARCHAR(20) default NULL,"
                        + "   last_name  VARCHAR(20) default NULL,"
                        + " salary     INT  default NULL,"
                        + " PRIMARY KEY (id)"
                        + "	);");
    }

    public static void sample5() {
        consumeStr(
                "create table CERTIFICATE ("
                        + "	   id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,"
                        + " certificate_name VARCHAR(30) default NULL,"
                        + " employee_id INT default NULL,"
                        + " PRIMARY KEY (id)"
                        + ");");
    }

    public static void sample2(String sql) {
        consumeStr(
                "Update complete for query: "
                        + consumeStr(sql)
                        + "<br>\n");
    }

    public static void sample1(String sql) {
        consumeStr("Update complete for query: " + sql + "\n");
    }

    private static String consumeStr(String str) {
        return str;
    }
}
