name: Analyzer release

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

jobs:
  publish:
    runs-on: [self-hosted, test]

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    container: cruizba/ubuntu-dind:focal-25.0.3
    permissions:
      contents: write
      packages: write

    steps:
      - name: Setup Git
        run: apt update && apt install -y git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Generate version
        id: version
        run: echo "version=$(date +'%Y.%m.%d').$(echo "${{ github.sha }}" | cut -c 1-7)" >> $GITHUB_OUTPUT

      - name: Build analyzer docker image
        run: ./gradlew :buildProjectAnalyzerDocker -PanalyzerVersion=${{ steps.version.outputs.version }}
        env:
          SEQRA_GITHUB_ACTOR: ${{ secrets.SEQRA_GITHUB_ACTOR }}
          SEQRA_GITHUB_TOKEN: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Create image names
        run: |
          echo "ANALYZER_IMAGE=ghcr.io/${{ github.repository_owner }}/seqra-jvm-sast/sast-analyzer:${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Tag images
        run: docker tag analyzer-private:${{ steps.version.outputs.version }} ${{ env.ANALYZER_IMAGE }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: docker push ${{ env.ANALYZER_IMAGE }}
